name: castalk
description: Castalk Mobile App for Android & iOS

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  smooth_page_indicator: ^1.0.0+2
  flutter_bloc: ^8.0.0
  pin_code_fields: ^7.3.0
  country_code_picker: ^2.0.2
  url_launcher: ^6.0.15
  multi_select_item: ^1.0.3
  blur: ^3.0.0
  flutter_svg: ^1.0.0
  music_slider: ^0.0.1
  modal_bottom_sheet: ^2.0.0
  expandable: ^5.0.1
  flutter_tags: ^0.4.9+1
  fl_chart: ^0.40.5
  dotted_border: ^2.0.0+2
  readmore: ^2.1.0
  flutter_sticky_header: ^0.6.0
  timelines: ^0.1.0
  flutter_slidable: ^1.1.0
  gradient_widgets: ^0.6.0
  rulers: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  assets:
  - assets/country_codes.txt
  - assets/icons/addlist.svg
  - assets/icons/download.svg
  - assets/icons/like.svg
  - assets/icons/share.svg
  - assets/icons/mic.svg
  - assets/icons/circle_left.svg
  - assets/icons/circle_righ.svg
  - assets/icons/comment.svg
  - assets/icons/forw.svg
  - assets/icons/playlist.svg
  - assets/icons/playlistheader.svg
  - assets/icons/pre.svg
  - assets/icons/setting.svg
  - assets/icons/pause.svg
  - assets/icons/repeat.svg
  - assets/icons/shuffle.svg
  - assets/icons/cast.svg
  - assets/icons/sleep.svg
  - assets/icons/carmode.svg
  - assets/icons/swipe.svg
  - assets/icons/carmode_outline.svg
  - assets/icons/radiochecked.svg
  - assets/icons/radiounchecked.svg
  - assets/icons/moredots.svg
  - assets/icons/modify.svg
  - assets/icons/search.svg
  - assets/icons/sort.svg
  - assets/icons/filter.svg
  - assets/icons/play.svg
  - assets/icons/download_prog.svg
  - assets/icons/timer.svg
  - assets/icons/heart_white.svg
  - assets/icons/arrow_left.svg
  - assets/icons/heart_empty.svg
  - assets/icons/info.svg
  - assets/icons/copy.svg
  - assets/icons/pizza.svg
  - assets/icons/close.svg
  - assets/icons/calendar.svg
  - assets/icons/arrow_down.svg
  - assets/icons/random.svg
  - assets/icons/delete.svg
  - assets/icons/newspaper.svg
  - assets/icons/tick.svg
  - assets/icons/webmoney.svg
  - assets/icons/paypal.svg
  - assets/icons/visa.svg
  - assets/icons/mastercard.svg
  - assets/icons/discover.svg
  - assets/icons/upload.svg
  - assets/icons/upload_image.svg
  - assets/icons/website.svg
  - assets/icons/instagram.svg
  - assets/icons/soundcloud.svg
  - assets/icons/spotify.svg
  - assets/icons/twitter.svg
  - assets/icons/youtube.svg
  - assets/icons/chartcenter.svg
  - assets/icons/arrow_right.svg
  - assets/icons/micdouble.svg
  - assets/icons/sharebold.svg
  - assets/icons/remove.svg
  - assets/icons/lock.svg
  - assets/icons/people_group.svg
  - assets/icons/dollarsign.svg
  - assets/icons/arrow_fish_right.svg
  - assets/icons/arrow_fish_left.svg
  - assets/icons/arrow_up.svg
  - assets/icons/coin.svg
  - assets/icons/folders.svg
  - assets/icons/send.svg
  - assets/icons/emoji.svg
  - assets/icons/add.svg
  - assets/icons/cut.svg
  - assets/icons/doc.svg
  - assets/icons/dotlist.svg
  - assets/icons/mosl.svg
  - assets/icons/mosr.svg
  - assets/icons/save.svg
  - assets/icons/sfx.svg
  - assets/icons/turn_left.svg
  - assets/icons/turn_right.svg
  - assets/icons/soundon.svg
  - assets/icons/soundoff.svg
  - assets/icons/redworm.svg
  - assets/icons/prevsound.svg
  - assets/icons/pausegold.svg
  - assets/icons/prevleft.svg
  - assets/icons/nextsound.svg
  - assets/icons/nextright.svg

  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
